### ISSUE TITLE
Update Vendored Vault Dependency to 1.1.x

### ISSUE THREAD

**Issue by lawliet89** [terraform-providers/terraform-provider-vault#333] opened 2019-03-01 02:10 UTC
I was trying to implement some new features for Vault 1.0 but I realised that the vendored Vault dependency is at `0.11.1` (!!!).

I tried taking a [stab](https://github.com/lawliet89/terraform-provider-vault/pull/new/vendor-vault-1.0.3) at this and I managed to build Vault but I am running into some nasty error running tests where Vault would report 

```
2019-03-01T10:10:02.275+0800 [DEBUG] core: non-timeout error accepting on cluster port: error="accept tcp 127.0.0.1:8201: accept4: too many open files"
```

and the tests never complete running. Somewhere along the way, some misbehaving dependency might be causing this.

I am new to Go and I have no clue how to get `govendor` to update Vault and all of its transitive dependencies. Could I get some help on this please?

@tyrannosaurus-becks

**Comment by cvbarros** [comment] 2019-03-15 21:48
Resolved via #292

**Comment by lawliet89** [comment] 2019-03-15 22:30
It's not resolved by that. The vendored libraries were not updated.

**Comment by cvbarros** [comment] 2019-03-15 22:37
Thats correct, just confirmed vendored dependency to 0.11. Got mistaken because I actually run the tests against `1.0.3` container and they work 🤷‍♂️

**Comment by lawliet89** [comment] 2019-03-15 22:45
It works because most of the secret engines and auth engines configuration
are done with generic writes and reads.

Some of the /sys endpoints have direct support in the library beyond just
generic reads and writes. I wanted to update the resource mounting auth
backends but I didn't want to reimplement what was already present in the
library using just the generic write methods.

**Comment by cvbarros** [comment] 2019-03-15 23:45
Better wait for #356 , it will make it a lot easier to manage dependencies moving forward.

**Comment by lawliet89** [comment] 2019-05-08 02:28
With the [switch to go modules](https://github.com/terraform-providers/terraform-provider-vault/pull/403) it's slightly easier to do this probably.

In any case, I tried to upgrade to v1.1.2 `go get github.com/hashicorp/vault@v1.1.2` and I am getting

```
build github.com/terraform-providers/terraform-provider-vault: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.1.2 (/home/yongwen/go/pkg/mod/github.com/hashicorp/vault@v1.1.2/api)
	github.com/hashicorp/vault/api v1.0.1 (/home/yongwen/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.1)
```

**Closed** 2019-06-03 17:43 UTC
